config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
  get 'about', to: 'home#about'
  resources :admins
  resources :courses
  resources :departments
  resources :scores
  resources :students
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get "/dashboard", to: "dashboard#index"
  resources :categories
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :username, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :scores, through: :student, dependent: :destroy

  validates :title, presence: true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :courses
  has_many :students
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
  belongs_to :course
  validates :number, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :score, through: :courses, dependent: :destroy
  belongs_to :department

  validates :name, presence: true
  validates :age, presence: true
  validates :matric_no, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_student, :logged_in?

  def current_student
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_student
    if !logged_in?
      flash[:alert] = "You are not authorized to view this page"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = "course was successfully created"
      redirect_to department_path(@course.department)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      flash[:notice] = "course was updated successfully"
      redirect_to department_path(@course.department)
    else
      render 'edit'
    end
  end

  def delete
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :department_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:notice] = "Department was successfully created"
      redirect_to departments_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      flash[:notice] = "Department was updated successfully"
      redirect_to department_path(@department)
    else
      render 'edit'
    end
  end

  def delete
  end

  private
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    student = Student.find_by(email: params[:session][:email].downcase)
    if student && student.authenticate(params[:session][:password])
      session[:student_id] = student.id
      flash[:notice] = "You have successfully logged in"
      redirect_to student
    else
      flash.now[:alert] = "Your login credentials were incorrect"
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :require_student, except: [:index, :show, :new, :create]
  before_action :require_same_student, only: [:edit, :update, :destroy]

  def index
    @student = Student.all
  end

  def show
    @student = Student.find(params[:id])

    # @student = @student.courses.all
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "Your profile was updated successfully"
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      session[:student_id] = @student.id
      flash[:notice] = "Welcome to your Student Portal 👉 #{@student.name.upcase} 👈"
      redirect_to student_path(@student)
    else
      render 'new'
    end
  end

  def destroy
    @student.destroy
    session[:student_id] = nil if @student == current_student
    flash[:delete] = "Account deleted successfully"
    redirect_to root_path
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :age, :matric_no, :department_id, :password, :password_confirmation)
  end

  def require_same_student
    if current_student != @student || !current_student.admin?
      flash[:alert] = "You are not authorized to view this page"
      redirect_to @student
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="flex flex-col justify-center items-center h-screen p-5">
  <h3 class="mb-20 text-4xl font-bold">Courses</h3>
  <div class="flex flex-col gap-y-5">
    <% @courses.each do |course| %>
      <%
=begin%>
 <%= link_to department.name, department_path(department) %> 
<%
=end%>
      <p><%= course.title %></p>
    <%end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="flex items-center justify-center h-screen">
  <div class="flex w-full lg:w-1/2 justify-center items-center bg-white space-y-8">
    <div class="w-full px-8 md:px-32 lg:px-24">
      <%= form_with(model: @course, class: 'shadow mb-3 p-5 bg-info roundedbg-white rounded-md shadow-2xl p-5', data: { turbo: false }) do |f| %>
        <h1 class="text-gray-800 font-bold text-2xl mb-8">Create Course!</h1>
        <div class="flex items-center border-2 mb-8 py-2 px-3 rounded-2xl">

          <svg
            class="h-5 w-5 text-gray-400"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <%= f.text_field :title, class: 'pl-2 w-full outline-none border-none', required: true, placeholder: 'Course Title' %>
        </div>

        <div class="flex items-center border-2 mb-8 py-2 px-3 rounded-2xl">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 text-gray-400">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.702 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
          </svg>
          <%= f.select(:department_id, Department.order(:name).map { |department| [department.name, department.id] }, { prompt: "Select your department from the list below" }, {class: 'pl-2 w-full outline-none border-none' }) %>
        </div>

        <%= f.submit "Save", class: 'block w-full bg-indigo-600 mt-5 py-2 rounded-2xl hover:bg-indigo-700 hover:-translate-y-1 transition-all duration-500 text-white font-semibold mb-2 hover:cursor-pointer' %>
      <% end %>
    </div>
    
  </div>
</div>

app/views/departments/index.html.erb
<div class="flex flex-col justify-center items-center h-screen p-5">
  <h3 class="mb-20 text-4xl font-bold">Departments</h3>
  <div class="flex flex-col gap-y-5 underline">
    <% @departments.each do |department| %>
      <%= link_to department.name, department_path(department) %>
    <%end %>
  </div>
</div>

app/views/departments/new.html.erb
<div class="flex items-center justify-center h-screen">
  <div class="flex w-full lg:w-1/2 justify-center items-center bg-white space-y-8">
    <div class="w-full px-8 md:px-32 lg:px-24">
      <%= form_with(model: @department, class: 'shadow mb-3 p-5 bg-info roundedbg-white rounded-md shadow-2xl p-5', data: { turbo: false }) do |f| %>
        <h1 class="text-gray-800 font-bold text-2xl mb-8">Create Department!</h1>
        <div class="flex items-center border-2 mb-8 py-2 px-3 rounded-2xl">

          <svg
            class="h-5 w-5 text-gray-400"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <%= f.text_field :name, class: 'pl-2 w-full outline-none border-none', required: true, placeholder: 'Department Name' %>
        </div>

        <%= f.submit "Save", class: 'block w-full bg-indigo-600 mt-5 py-2 rounded-2xl hover:bg-indigo-700 hover:-translate-y-1 transition-all duration-500 text-white font-semibold mb-2 hover:cursor-pointer' %>
      <% end %>
    </div>
    
  </div>
</div>

app/views/departments/show.html.erb
<div class="flex flex-col justify-center items-center h-screen p-5">
  <h3 class="mb-20 text-4xl font-bold"><%= @department.name %></h3>
  <div class="grid grid-cols-2 gap-10">
    <div class="flex flex-col gap-y-5 underline">
      <h2 class="font-bold text-lg">Courses</h2>
      <% @department.courses.each do |course| %>
        <%= link_to course.title, department_path(course) %>
      <%end %>
    </div>
    <div class="flex flex-col gap-y-5 underline">
      <h2 class="font-bold text-lg">Students</h2>
      <% @department.students.each do |student| %>
        <%= link_to student.name, student_path(student) %>
      <%end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="w-full h-screen flex flex-col">
    <nav class="bg-white shadow-lg">
        <div class="md:flex items-center justify-between py-2 px-8 md:px-12">
            <div class="flex justify-between items-center">
              <div class="text-2xl font-bold text-gray-800 md:text-3xl">
                <a href="#">STUDENT PORTAL</a>
              </div>
              <div class="md:hidden">
                <button type="button" class="block text-gray-800 hover:text-gray-700 focus:text-gray-700 focus:outline-none">
                  <svg class="h-6 w-6 fill-current" viewBox="0 0 24 24">
                      <path class="hidden" d="M16.24 14.83a1 1 0 0 1-1.41 1.41L12 13.41l-2.83 2.83a1 1 0 0 1-1.41-1.41L10.59 12 7.76 9.17a1 1 0 0 1 1.41-1.41L12 10.59l2.83-2.83a1 1 0 0 1 1.41 1.41L13.41 12l2.83 2.83z"/>
                      <path d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/>
                  </svg>
                </button>
              </div>
            </div>
            <div class="flex flex-col md:flex-row hidden md:block -mx-2">
                <a href="#" class="text-gray-800 rounded hover:bg-gray-900 hover:text-gray-100 hover:font-medium py-2 px-2 md:mx-2">Home</a>
                <a href="#" class="text-gray-800 rounded hover:bg-gray-900 hover:text-gray-100 hover:font-medium py-2 px-2 md:mx-2">About</a>
                <a href="#" class="text-gray-800 rounded hover:bg-gray-900 hover:text-gray-100 hover:font-medium py-2 px-2 md:mx-2">Contact</a>
            </div>
        </div>
    </nav>
    <div class="flex bg-white grow">
        <div class="flex items-center text-center lg:text-left px-8 md:px-12 lg:w-1/2">
            <div>
                <h2 class="text-3xl font-semibold text-gray-800 md:text-4xl">Result Portal for <span class="text-indigo-600">Students</span></h2>
                <p class="mt-2 text-sm text-gray-500 md:text-base">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis commodi cum cupiditate ducimus, fugit harum id necessitatibus odio quam quasi, quibusdam rem tempora voluptates. Cumque debitis dignissimos id quam vel!</p>
                <div class="flex justify-center lg:justify-start mt-6">
                    <%= link_to "Get Started", new_student_path, class: "px-4 py-3 bg-gray-900 text-gray-200 text-xs font-semibold rounded hover:bg-gray-800" %>
                    <a class="mx-4 px-4 py-3 bg-gray-300 text-gray-900 text-xs font-semibold rounded hover:bg-gray-400" href="#">Learn More</a>
                </div>
            </div>
        </div>
        <div class="hidden lg:block lg:w-1/2" style="clip-path:polygon(10% 0, 100% 0%, 100% 100%, 0 100%)">
            <div class="h-full object-cover" style="background-image: url(https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80)">
                <div class="h-full bg-black opacity-25"></div>
            </div>
        </div>
    </div>
    <div>
      <section class="bg-black">
       <div
            class="max-w-lg bg-black px-4 pt-24 py-8 mx-auto text-left md:max-w-none md:text-center"
          >
            <h1
              class="text-3xl font-extrabold leading-10 tracking-tight text-left text-white text-center sm:leading-none md:text-6xl text-4xl lg:text-7xl"
            >
              <span class="inline md:block">Sign In To</span>
              <span
                class=" mt-2 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-emerald-400 to-green-500 md:inline-block"
              > Check Your<span class="bg-clip-text text-transparent bg-gradient-to-r from-teal-500 via-cyon-400 to-purple-300"> Results</span> </span>
            </h1>
            <div
              class="mx-auto rounded-lg font-black mt-5 text-zinc-400 md:mt-12 md:max-w-lg text-center lg:text-lg"
            >
              <%= link_to "Login", login_path, class: "bg-tkb border text-sm text-white py-3 px-7 rounded-full" %>
            </div>
          </div>
  </section>
  
  <hr class="text-white mx-5" />
  <footer class="bg-black pb-5">
      <div class="max-w-screen-xl px-4 pt-8 mx-auto sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center sm:justify-between">
          <div class="flex justify-center text-teal-300 sm:justify-start">
            <h3 class="text-xl font-bold">Student Portal</h3>
          </div>

          <p class="mt-4 text-sm text-center text-gray-400 lg:text-right lg:mt-0">
            T&C &nbsp; Career &nbsp; Privacy & Policy &nbsp; <a>Admin</a>
          </p>
        </div>
      </div>
  </footer>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main>
      <%= render 'components/notice' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/students/show.html.erb
<div
      id="view"
      class="h-full w-screen flex flex-row"
      x-data="{ sidenav: true }"
>
  <button
    @click="sidenav = true"
    class="p-2 border-2 bg-white rounded-md border-gray-200 shadow-lg text-gray-500 focus:bg-teal-500 focus:outline-none focus:text-white absolute top-0 left-0 sm:hidden"
  >
    <svg
      class="w-5 h-5 fill-current"
      fill="currentColor"
      viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fill-rule="evenodd"
        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
        clip-rule="evenodd"
      ></path>
    </svg>
  </button>
  <div
    id="sidebar"
    class="bg-white h-screen md:block shadow-xl px-3 w-30 md:w-60 lg:w-60 overflow-x-hidden transition-transform duration-300 ease-in-out"
    x-show="sidenav"
    @click.away="sidenav = false"
  >
    <div class="space-y-6 md:space-y-10 mt-10">
      <h1 class="font-bold text-4xl text-center md:hidden">
        D<span class="text-teal-600">.</span>
      </h1>
      <h1 class="hidden md:block font-bold text-sm md:text-xl text-center">
        Student Portal<span class="text-teal-600">.</span>
      </h1>
      <div id="profile" class="space-y-3">
        <img
          src="https://images.unsplash.com/photo-1628157588553-5eeea00af15c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80"
          alt="Avatar user"
          class="w-10 md:w-16 rounded-full mx-auto"
        />
        <div>
          <h2
            class="font-medium text-xs md:text-sm text-center text-teal-500"
          >
            <%= @student.name %>
          </h2>
          <p class="text-xs text-gray-500 text-center">
          <%if @student.admin? %>
            <%= "ADMIN" %>
            <% else %>
            <%= @student.department.name %>
          <% end %>
          </p>
        </div>
      </div>
      <div
        class="flex border-2 border-gray-200 rounded-md focus-within:ring-2 ring-teal-500"
      >
        <input
          type="text"
          class="w-full rounded-tl-md rounded-bl-md px-2 py-3 text-sm text-gray-600 focus:outline-none"
          placeholder="Search"
        />
        <button
          class="rounded-tr-md rounded-br-md px-2 py-3 hidden md:block"
        >
          <svg
            class="w-4 h-4 fill-current"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </div>
      <div id="menu" class="flex flex-col space-y-2">
        <a
          class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-teal-500 hover:text-white hover:text-base rounded-md transition duration-150 ease-in-out"
        >
          <svg
            class="w-6 h-6 fill-current inline-block"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"
            ></path>
          </svg>
          <span class="">Dashboard</span>
        </a>
        <a
          class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-teal-500 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out"
        >
          <svg
            class="w-6 h-6 fill-current inline-block"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z"></path>
            <path
              fill-rule="evenodd"
              d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm3 4a1 1 0 000 2h.01a1 1 0 100-2H7zm3 0a1 1 0 000 2h3a1 1 0 100-2h-3zm-3 4a1 1 0 100 2h.01a1 1 0 100-2H7zm3 0a1 1 0 100 2h3a1 1 0 100-2h-3z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <span class="">Results</span>
        </a>
        <a
          class="text-sm font-medium text-gray-700 py-2 px-2 hover:bg-teal-500 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out"
        >
          <svg
            class="w-6 h-6 fill-current inline-block"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fill-rule="evenodd"
              d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
              clip-rule="evenodd"
            ></path>
          </svg>
          <span class="">Courses</span>
        </a>

        <%= button_to logout_path, class: "w-full text-sm text-left font-medium text-red-700 py-2 px-2 hover:bg-teal-500 hover:text-white hover:scale-105 rounded-md transition duration-150 ease-in-out", method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 fill-current inline-block">
            <path fill-rule="evenodd" d="M7.5 3.75A1.5 1.5 0 006 5.25v13.5a1.5 1.5 0 001.5 1.5h6a1.5 1.5 0 001.5-1.5V15a.75.75 0 011.5 0v3.75a3 3 0 01-3 3h-6a3 3 0 01-3-3V5.25a3 3 0 013-3h6a3 3 0 013 3V9A.75.75 0 0115 9V5.25a1.5 1.5 0 00-1.5-1.5h-6zm5.03 4.72a.75.75 0 010 1.06l-1.72 1.72h10.94a.75.75 0 010 1.5H10.81l1.72 1.72a.75.75 0 11-1.06 1.06l-3-3a.75.75 0 010-1.06l3-3a.75.75 0 011.06 0z" clip-rule="evenodd" />
          </svg>

          <span class="">Log out</span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="grow">
    <div class="container p-5 pt-20">
      <div class="border shadow rounded-lg flex flex-col gap-y-10 p-5">
        <div class="flex justify-between font-bold text-lg">
          <p>Courses</p>
          <p>Score</p>
        </div>
        <% @student.department.courses.each do |course| %>
          <div class="flex justify-between">
            <h2><%= course.title %></h2>

            <h3><%= 0 %></h3>  
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>